config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :ingredients

  root 'welcome#index'

  get 'new' => 'ingredient#new'

  get 'welcome/about'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	has_many :recipe_ingredients
	has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :recipe_ingredients
	has_many :ingredients, through: :recipe_ingredients
	accepts_nested_attributes_for :ingredients

	mount_uploader :image, ImageUploader
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
	belongs_to :recipe
	belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create

    @recipe = Recipe.create(recipe_params)

    ingredient_params.each do |ing|
      @recipe.ingredients << Ingredient.find_or_create_by(ing)
    end


    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :instructions, :est_time, :image)
    end

    def ingredient_params
      params.require(:recipe).require(:ingredients_attributes).values.map{|x| {name: x[:name]}}
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<form>
  <div class="form-group">
    <%= form.text_field :name, id: :ingredient_name, class:'form-control', placeholder:'Enter an ingredient...' %>
  </div>
  <button type="submit" class="btn btn-success">Add</button>
</form>

<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients <%= link_to ' ', new_ingredient_path, class:'fas fa-plus' %></h1>

<div class="row">
  <% @ingredients.each do |ingredient| %>
    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <%= link_to ingredient.name, ingredient %>   <%= link_to ' ', ingredient, class: 'fas fa-trash', method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/ingredients/new.html.erb
<h3>Add an Ingredient</h3>

<div class="container">
	<%= render 'form', ingredient: @ingredient %>
</div>

<br />

<%= link_to '', ingredients_path, class:'fas fa-angle-double-left fa-2x' %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @ingredient.name %></h1>

<div class="row">
	<% @ingredient.recipes.each do |rec| %>
  	<div class="col-sm-4">
  		<%= render 'recipes/recipe', rec: rec %>
  	</div>
	<% end %>
</div>



<!--loop to display recipe cards with recipes with that ingredient
	loop over recipe table and if ... include?  -->

<%= link_to '', ingredients_path, class:'fas fa-angle-double-left fa-3x'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DateNight</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-brand"><%= link_to 'Recipe Box', root_path %></div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <div class="nav-item nav-link active"><%= link_to 'Home', root_path %></div>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Ingredients </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li class="dropdown-item"><%= link_to 'All Ingredients', ingredients_path %></li>
              <li class="dropdown-item"><%= link_to 'New Ingredient', new_ingredient_path%></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Recipes</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li class="dropdown-item"><%= link_to 'All Recipes', recipes_path %></li>
              <li class="dropdown-item"><%= link_to 'New Recipe', new_recipe_path%></li>
            </ul>
          </li>
        </div>
      </div>
  </nav>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name, id: :recipe_name, class:'form-control', placeholder:'Enter name of recipe...' %>
  </div>
  <div class="form-group">
    <%= form.text_area :instructions, id: :recipe_instructions, class:'form-control', placeholder:'Tell me how you make that again...'%>
  </div>
  <div class="form-group">
    <%= form.number_field :est_time, id: :recipe_est_time, class:'form-control', placeholder: 'How long does this dish take to make?'%>
  </div>
  <div class="form-group">
    <h4>Ingredients</h4>
    <%= form.fields_for :ingredients do |ingredient| %>
      <%= render 'ingredient_fields', f: ingredient %>
    <% end %>
    <div class="links">
      <%= link_to_add_association form, :ingredients, class: 'fas fa-plus' do %>
      <% end %>
    </div>
  </div>
  <%= form.submit class:'btn btn-success' %>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields form-group">
	<%= f.text_field :name %>
</div>

app/views/recipes/_recipe.html.erb
<div class = "card">
  <div class="card-body">
    <div class="card-header">
      <p><strong><%= link_to rec.name, rec %></strong></p>
    </div>
    <div class="card-text">
      <h4><strong>Instructions:</strong></h4>
      <p><%= rec.instructions %></p>
      <h4>Ingredients</h4>
      <p>
        <% rec.ingredients.each do |ing| %>
        <%= link_to ing.name, ing %> 
        <% end %>
      </p>
      <h6>Est: time:</h6> <p><%= rec.est_time %> mins</p>
    </div>
    <div class="card-footer">
      <table>
        <tr>
          <td><%= link_to ' ', edit_recipe_path(rec), class: 'far fa-edit' %></td>
          <td><%= link_to ' ', rec, class: 'fas fa-trash', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Recipes</h1>

<div class="row">
  <% @recipes.each do |recipe| %>
    <div class="col-sm-4">
      <%= render 'recipe', rec: recipe %>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<br />
<br />
<%= link_to '', recipes_path, class:'fas fa-angle-double-left fa-3x' %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<!-- Build Card or jumbotron for recipe with side bar -->

<div class="row">
	<div class="col-lg-9">
		<div class="card border-dark mb-3">
			<div class="card-header">
				<h2><%= @recipe.name %><div class="far fa-clock"></div><%= @recipe.est_time %> mins</h2>
			</div>
			<div class="card-body">
				<h3>Instructions</h3>
				<p><%= @recipe.instructions %></p>
			</div>
		</div>
	</div>
	<div class="col-lg-3">
		<div class="card">
			<div class="card-header">
				Ingredients
			</div>
			<div class="card-body">
				<% @recipe.ingredients.each do |ing| %>
					<table>
						<tr>
							<td><%= link_to ing.name%></td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
	</div>
</div>



<%= link_to ' ', recipes_path, class:'fas fa-angle-double-left fa-3x' %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Choose a View:</h1>
    <br />
    <p>
  	<%= link_to 'Recipes', recipes_path, class:'btn btn-xlarge' %>
  	<%= link_to 'Ingredients', ingredients_path, class:'btn btn-xlarge' %>
  </p>
</div>